
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: pizzeria_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzeria
      MYSQL_USER: pizzeria_user
      MYSQL_PASSWORD: pizzeria_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    command: --default-authentication-plugin=mysql_native_password
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pizzeria_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: pizzeria_user
      PMA_PASSWORD: pizzeria_password
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
